#! usr/bin/env python
# -*- coding:utf-8 -*-


__anthor__ = 'HMC'

import threading , asyncio

@asyncio.coroutine
def hello():
	print('hello world! (%s)' % threading.currentThread())
	yield from asyncio.sleep(1)
	print('complete hello()')
def otherhello():
	print('hello otherworld! (%s)' % threading.currentThread())
	yield from asyncio.sleep(1)
	print('complete otherhello()')

loop = asyncio.get_event_loop()
tasks=[hello(),otherhello()]
loop.run_until_complete(asyncio.wait(tasks))
loop.close()