#! usr/bin/env python
# -*- coding:utf-8 -*-

__anthor__ = 'hmc'

class Stack():
	def __init__(self,size):
		self.stack = []
		self.size = size
		self.top = -1

	def push(self,content):
		if self.full():
			print('stack is full')
		else:
			self.stack.append(content)
			self.top += 1

	def out(self):
		if self.empty():
			print('stack is empty')
		else:
			self.stack.pop()
			self.top -= 1
	def full(self):
		if self.size == self.top:
			return True
		else:
			return False
	def empty(self):
		if self.top == -1:
			return True
		else:
			return False


if __name__ =='__main__':
	kk = Stack(3)
	kk.push(1)
	print(kk.stack)
	kk.push(2)
	print(kk.stack)
	kk.out()
	print(kk.top)
	print(kk.stack)
	kk.out()
	kk.out()
	kk.out()
	print(kk.top)
